/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/jGWbSfjBaoX
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import Image from "next/image"

export function ContactPage() {
  return (
    <div className="container mx-auto">
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container grid gap-12 px-4 md:px-6 lg:grid-cols-2 lg:gap-24">
          <div className="space-y-4">
            <div className="flex items-center gap-4">
            <Image src={'/logo.png'} alt="logo" width={80} height={80} />
              <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Poly observer news</h1>
            </div>
            <p className="text-gray-500">
              Poly observer is a leading media and news company that owns a popular blog website. We cover a wide range of
              topics, from politics and business to entertainment and lifestyle. Our team of experienced journalists and
              editors work tirelessly to provide our readers with the latest news, analysis, and insights.
            </p>
            <div className="space-y-2">
              <h3 className="text-xl font-bold">Our Location</h3>
              <div className="text-gray-500 dark:text-gray-400">
                <p>123 Main Street, AnytownBT</p>
                <p>Phone: (123) 456-7890</p>
                <p>Email: info@polyobserver.com</p>
              </div>
            </div>
            <div className="space-y-2">
              <h3 className="text-xl font-bold">Our Mission</h3>
              <p className="text-gray-500 dark:text-gray-400">
                At Poly observer, our mission is to deliver accurate, unbiased, and timely news to our readers. We strive to
                be a trusted source of information, helping our audience stay informed about the world around them. Our
                team is dedicated to upholding the highest journalistic standards and providing valuable insights that
                empower our readers to make informed decisions.
              </p>
            </div>
            <div className="space-y-2">
              <h3 className="text-xl font-bold">Our Team</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Our team of journalists, editors, and content creators are passionate about their craft and committed to
                delivering exceptional content to our readers. With diverse backgrounds and expertise, we work
                collaboratively to cover a wide range of topics and provide a comprehensive news experience.
              </p>
            </div>
          </div>
          <div className="grid gap-6">
            <form className="space-y-4">
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <div className="space-y-2">
                  <Label htmlFor="name">Name</Label>
                  <Input className="bg-gray-100" id="name" placeholder="Enter your name" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="email">Email</Label>
                  <Input className="bg-gray-100" id="email" type="email" placeholder="Enter your email" />
                </div>
              </div>
              <div className="space-y-2">
                <Label htmlFor="subject">Subject</Label>
                <Input className="bg-gray-100" id="subject" placeholder="Enter the subject" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="message">Message</Label>
                <Textarea id="message" placeholder="Enter your message" className="min-h-[150px]" />
              </div>
              <Button type="submit" className="w-full">
                Submit
              </Button>
            </form>
            <div className="space-y-4">
              <div className="space-y-2">
                <h3 className="text-xl font-bold">Contact Us</h3>
                <div className="space-y-1 text-gray-500 dark:text-gray-400">
                  <p>123 Main Street, Anytown BT</p>
                  <p>Phone: (123) 456-7890</p>
                  <p>Email: info@polyobserver.com</p>
                  <div className="flex items-center gap-2">
                    <Link href="#" className="hover:underline" prefetch={false}>
                      <TwitterIcon className="h-6 w-6" />
                    </Link>
                    <Link href="#" className="hover:underline" prefetch={false}>
                      <FacebookIcon className="h-6 w-6" />
                    </Link>
                    <Link href="#" className="hover:underline" prefetch={false}>
                      <InstagramIcon className="h-6 w-6" />
                    </Link>
                  </div>
                </div>
              </div>
              <div className="space-y-2">
                <h3 className="text-xl font-bold">Our Partners</h3>
                <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4">
                  <Link href="#" className="hover:underline" prefetch={false}>
                    <img
                      src="/placeholder.svg"
                      width={100}
                      height={50}
                      alt="Partner Logo"
                      className="aspect-[2/1] object-contain"
                    />
                  </Link>
                  <Link href="#" className="hover:underline" prefetch={false}>
                    <img
                      src="/placeholder.svg"
                      width={100}
                      height={50}
                      alt="Partner Logo"
                      className="aspect-[2/1] object-contain"
                    />
                  </Link>
                  <Link href="#" className="hover:underline" prefetch={false}>
                    <img
                      src="/placeholder.svg"
                      width={100}
                      height={50}
                      alt="Partner Logo"
                      className="aspect-[2/1] object-contain"
                    />
                  </Link>
                  <Link href="#" className="hover:underline" prefetch={false}>
                    <img
                      src="/placeholder.svg"
                      width={100}
                      height={50}
                      alt="Partner Logo"
                      className="aspect-[2/1] object-contain"
                    />
                  </Link>
                  <Link href="#" className="hover:underline" prefetch={false}>
                    <img
                      src="/placeholder.svg"
                      width={100}
                      height={50}
                      alt="Partner Logo"
                      className="aspect-[2/1] object-contain"
                    />
                  </Link>
                  <Link href="#" className="hover:underline" prefetch={false}>
                    <img
                      src="/placeholder.svg"
                      width={100}
                      height={50}
                      alt="Partner Logo"
                      className="aspect-[2/1] object-contain"
                    />
                  </Link>
                  <Link href="#" className="hover:underline" prefetch={false}>
                    <img
                      src="/placeholder.svg"
                      width={100}
                      height={50}
                      alt="Partner Logo"
                      className="aspect-[2/1] object-contain"
                    />
                  </Link>
                  <Link href="#" className="hover:underline" prefetch={false}>
                    <img
                      src="/placeholder.svg"
                      width={100}
                      height={50}
                      alt="Partner Logo"
                      className="aspect-[2/1] object-contain"
                    />
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}

function FacebookIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function InstagramIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}


function MountainIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function TwitterIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}
