/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/me4r9MYCTdo
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { DM_Serif_Display } from 'next/font/google'

dm_serif_display({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { prisma } from "@/lib/connect";
import Image from "next/image";
import Link from "next/link"

export async function Finisher() {

  const categories = await prisma.category.findMany({
    orderBy:{
      visitors:"desc"
    },
    take:6
  });

  return (
    <div className=" bg-gray-100 py-10 mt-20 px-2 md:px-0">
      <div className="container mx-auto">
        <div className="flex flex-col md:flex-row gap-1 items-center">
          <h2 className="text-2xl font-bold mb-4">Popular Categories</h2>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            {categories.map(category=>(
              <Link
              href={`/categories/${category.title}`}
              key={category.id}
              className="flex items-center gap-2 border-b md:border-b-0 md:border-r  p-2 cursor-pointer hover:underline"
              prefetch={false}
            >
              <Image
                src={`${category.img}`}
                alt="Article Thumbnail"
                width={500}
                height={500}
                className="aspect-[4/4] shrink-0 w-20 h-20 overflow-hidden object-cover"
              />
              <div className="">
                  <h3 className=" font-bold text-black">{category.title}</h3>
                  <p className='text-xs text-gray-600'>{category.description}</p>
              </div>
            </Link>
            ))}
            
          </div>
        </div>
      </div>
    </div>
  )
}
