/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/s82cvsBWUYm
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Input } from "@/components/ui/input"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function Quotes() {
  return (
    <div className="flex min-h-[100dvh] w-full">
      <div className="flex flex-col items-center justify-center bg-background px-4 py-12 sm:px-6 lg:px-8 w-full max-w-md">
        <div className="mx-auto w-full space-y-6">
          <div className="text-center">
            <h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Quote of the Day</h1>
            <p className="mt-2 text-muted-foreground">Input the quote you want to display today.</p>
          </div>
          <div className="grid gap-4">
            <div>
              <Label htmlFor="quote">Quote</Label>
              <Textarea
                id="quote"
                rows={4}
                placeholder="Enter your quote here..."
                className="mt-1 block w-full rounded-md border-input bg-background text-foreground shadow-sm focus:border-primary focus:ring-primary"
              />
            </div>
            <div>
              <Label htmlFor="author">Author</Label>
              <Input
                id="author"
                placeholder="Enter the author's name"
                className="mt-1 block w-full rounded-md border-input bg-background text-foreground shadow-sm focus:border-primary focus:ring-primary"
              />
            </div>
          </div>
          <div>
            <Card className="bg-muted p-6">
              <blockquote className="text-center text-2xl font-medium leading-relaxed text-foreground">
                &ldquo;&rdquo;
              </blockquote>
              <div className="mt-4 text-center text-muted-foreground" />
            </Card>
          </div>
          <div className="flex justify-end">
            <Button type="submit" className="bg-primary text-primary-foreground hover:bg-primary/90">
              Save Quote
            </Button>
          </div>
        </div>
      </div>
      <div className="bg-muted p-6 w-full max-w-md">
        <h2 className="text-xl font-bold mb-4">Generated Quotes</h2>
        <div className="space-y-4">
          <Card className="p-4">
            <blockquote className="text-lg font-medium leading-relaxed text-foreground">
              &ldquo;The only way to do great work is to love what you do.&rdquo;
            </blockquote>
            <div className="mt-2 text-muted-foreground">Steve Jobs</div>
          </Card>
          <Card className="p-4">
            <blockquote className="text-lg font-medium leading-relaxed text-foreground">
              &ldquo;Believe you can and you are halfway there.&rdquo;
            </blockquote>
            <div className="mt-2 text-muted-foreground">Theodore Roosevelt</div>
          </Card>
          <Card className="p-4">
            <blockquote className="text-lg font-medium leading-relaxed text-foreground">
              &ldquo;The future belongs to those who believe in the beauty of their dreams.&rdquo;
            </blockquote>
            <div className="mt-2 text-muted-foreground">Eleanor Roosevelt</div>
          </Card>
        </div>
      </div>
    </div>
  )
}
