/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/KXIfDHLMku5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { prisma } from "@/lib/connect";
import { getQuoteOfTheDay } from "@/lib/getDailyQuote";

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export async function QuoteOfADay() {

  const quotes = await prisma.quotes.findMany()
  const quote = getQuoteOfTheDay(quotes);

  return (
    <div className="bg-gray-100 bg-dot py-12 dark:bg-gray-800">
      <div className="container mx-auto px-4 md:px-6">
        <div className=" relative bg-gray-100  mx-auto max-w-2xl  p-2 border-8 text-center">
          <div className="absolute -top-4  inset-x-0 flex justify-center">
            <div className="mb-6 inline-flex items-center rounded-full bg-gray-200 px-4 py-1 text-sm font-medium text-gray-600 dark:bg-gray-700 dark:text-gray-400">
              <LightbulbIcon className="mr-2 h-4 w-4" />
              Quote of the Day
            </div>
          </div>
          <blockquote className="space-y-4 mt-3">
            <p className="text-2xl font-semibold leading-tight text-gray-800 dark:text-gray-200 animate__animated animate__backInDown">
              &ldquo;{quote.content}&rdquo;
            </p>
            <div className="text-gray-500 dark:text-gray-400">- {quote.author}</div>
          </blockquote>
        </div>
      </div>
    </div>
  )
}

function LightbulbIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5" />
      <path d="M9 18h6" />
      <path d="M10 22h4" />
    </svg>
  )
}


function RocketIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z" />
      <path d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z" />
      <path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0" />
      <path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" />
    </svg>
  )
}
