/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/c9TPAvdfBo6
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Checkbox } from "@/components/ui/checkbox"
import { Button } from "@/components/ui/button"
import { Chrome } from "lucide-react"
import Image from "next/image"

export function Signin() {
  return (
    <div className="grid md:grid-cols-2 items-center justify-center bg-black text-white rounded-md m-4 px-4 py-12 sm:px-6 lg:px-8 dark:bg-gray-950">
      <div className="flex justify-center items-center">
       <Image alt="large logo" src={'/logo.png'} width={500} height={500} className="hidden md:block" />
      </div>
     
      <div className="space-y-8">
        <div>
          <p className="mt-6 text-7xl font-bold dark:text-gray-50">
            Its Happening Now
          </p>
          <p className="mt-2 text-4xl dark:text-gray-400">
            Join Now!
          </p>
        </div>
        <div className="flex flex-col gap-2">
          <Button className="border-none outline-none rounded-3xl bg-white text-gray-500 font-extrabold w-[20rem]">Use google</Button>
          <Button className="border-none outline-none rounded-3xl bg-white text-gray-500 font-extrabold w-[20rem]">Use credetials</Button>
        </div>

        <p>Or</p>
        <Button className="border-none outline-none rounded-3xl bg-blue-500 text-white text-md font-extrabold w-[20rem]">Create Account</Button>
        <p className="text-xs max-w-sm">By signing up, you agree to the Terms of Service and Privacy Policy, including Cookie Use.</p>
        
           
      </div>
      <div className="border-t w-full mt-10 pt-3">
          <div className="space-y-2">
            <p className="text-xl font-extrabold">
              Welcome to Poly Observer
            </p>
            <p className="text-xs text-gray-500">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Soluta, quia eum reiciendis autem neque ipsam debitis placeat sint tempore dolorem aperiam delectus excepturi! Delectus eum reprehenderit optio tempora provident numquam?</p>
          </div>
        </div>
    </div>
  )
}

