/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/GRlcOVtzuD9
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Prata } from 'next/font/google'
import { Yeseva_One } from 'next/font/google'

prata({
  subsets: ['latin'],
  display: 'swap',
})

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import Link from "next/link"
import Image from "next/image"
import { prisma } from "@/lib/connect"

export async function SingleCategory({category}:{category:string}) {

  const [newCategoryArticle, requiredCategory] = await prisma.$transaction([

     prisma.article.findFirst({
      where:{
        catSlug:category
      },
      orderBy:{
        createdAt:"desc"
      }
    }),
     prisma.category.findFirst({
      where:{
        title:category
      },
   
    })

  ])


  

  return (
    <div className=" md:min-h-screen  text-white bg-black">
      <div className="grid md:grid-cols-2 items-center gap-1">
        <div className="md:ml-20  mt-20 md:mt-0">
          <p className="text-[#B8860B] text-sm md:text-md text-center uppercase">{category} <span className="text-[red] font-bold">.</span> <span className="text-white">NEW</span></p>
          <h2 className="text-2xl text-center md:text-7xl">{newCategoryArticle?.title}</h2>
          <p className="text-center mt-10">
          <Link href={`/view/${newCategoryArticle?.id}?cat=${newCategoryArticle?.catSlug}`} className="underline" >
            Read now
          </Link></p>
          
        </div>
        <img src={`${requiredCategory?.img}`} alt="" height={100} width={100} className=" w-full" />
      </div>
    </div>
  )
}

function ArrowRightIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}

function CalendarIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function UserIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
