/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1PvTNyT0EVJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion"
import { Label } from "@/components/ui/label"
import { Checkbox } from "@/components/ui/checkbox"
import { Card, CardContent, CardFooter } from "@/components/ui/card"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { prisma } from "@/lib/connect"

export async function Vacancy() {

  const Vacancy = await prisma.vacancy.findMany({
    orderBy:{
      createdAt:"desc"
    }
  })
  return (
    <div className="container mx-auto px-4 py-8 md:px-6 lg:px-8">
      <div className="grid grid-cols-1 md:grid-cols-[300px_1fr] gap-8">
        <div className="bg-gray-100 rounded-lg p-6 dark:bg-gray-800">
          <h2 className="text-2xl font-bold mb-4">Filters</h2>
          <Accordion type="single" collapsible>
            <AccordionItem value="category">
              <AccordionTrigger className="text-lg font-medium">Category</AccordionTrigger>
              <AccordionContent>
                <div className="grid gap-2">
                  <Label className="flex items-center gap-2 font-normal">
                    <Checkbox id="category-marketing" /> Marketing
                  </Label>
                  <Label className="flex items-center gap-2 font-normal">
                    <Checkbox id="category-engineering" /> Engineering
                  </Label>
                  <Label className="flex items-center gap-2 font-normal">
                    <Checkbox id="category-design" /> Design
                  </Label>
                  <Label className="flex items-center gap-2 font-normal">
                    <Checkbox id="category-sales" /> Sales
                  </Label>
                  <Label className="flex items-center gap-2 font-normal">
                    <Checkbox id="category-finance" /> Finance
                  </Label>
                </div>
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="job-type">
              <AccordionTrigger className="text-lg font-medium">Job Type</AccordionTrigger>
              <AccordionContent>
                <div className="grid gap-2">
                  <Label className="flex items-center gap-2 font-normal">
                    <Checkbox id="job-type-full-time" /> Full-Time
                  </Label>
                  <Label className="flex items-center gap-2 font-normal">
                    <Checkbox id="job-type-part-time" /> Part-Time
                  </Label>
                  <Label className="flex items-center gap-2 font-normal">
                    <Checkbox id="job-type-contract" /> Contract
                  </Label>
                  <Label className="flex items-center gap-2 font-normal">
                    <Checkbox id="job-type-internship" /> Internship
                  </Label>
                </div>
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="location">
              <AccordionTrigger className="text-lg font-medium">Location</AccordionTrigger>
              <AccordionContent>
                <div className="grid gap-2">
                  <Label className="flex items-center gap-2 font-normal">
                    <Checkbox id="location-new-york" /> New York
                  </Label>
                  <Label className="flex items-center gap-2 font-normal">
                    <Checkbox id="location-san-francisco" /> San Francisco
                  </Label>
                  <Label className="flex items-center gap-2 font-normal">
                    <Checkbox id="location-london" /> London
                  </Label>
                  <Label className="flex items-center gap-2 font-normal">
                    <Checkbox id="location-remote" /> Remote
                  </Label>
                </div>
              </AccordionContent>
            </AccordionItem>
          </Accordion>
        </div>
        <div>
          <div className="mb-6 text-black">
            <h1 className="text-3xl font-bold">Job Openings</h1>
            <p className="text-gray-500 dark:text-gray-400">Browse our latest job listings and apply today.</p>
          </div>
          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            <Card className="relative overflow-hidden group">
              <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                <span className="sr-only">View job</span>
              </Link>
              <CardContent className="p-6">
                <h3 className="text-xl font-bold mb-2">Senior Marketing Manager</h3>
                <p className="text-gray-500 mb-4 dark:text-gray-400">
                  Responsible for developing and executing marketing strategies to drive growth and brand awareness.
                </p>
                <div className="flex items-center gap-4 mb-4">
                  <MapPinIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-gray-500 dark:text-gray-400">New York, NY</span>
                </div>
                <div className="flex items-center gap-4">
                  <CalendarIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-gray-500 dark:text-gray-400">Application Deadline: June 30, 2023</span>
                </div>
              </CardContent>
              <CardFooter className="bg-gray-100 p-4 transition-colors group-hover:bg-gray-100 group-hover:text-gray-900 dark:bg-gray-800 dark:group-hover:bg-gray-800 dark:group-hover:text-gray-50">
                <Button variant="outline" className="w-full">
                  Apply Now
                </Button>
              </CardFooter>
            </Card>
            <Card className="relative overflow-hidden group">
              <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                <span className="sr-only">View job</span>
              </Link>
              <CardContent className="p-6">
                <h3 className="text-xl font-bold mb-2">Front-End Developer</h3>
                <p className="text-gray-500 mb-4 dark:text-gray-400">
                  Develop and maintain modern, responsive web applications using the latest front-end technologies.
                </p>
                <div className="flex items-center gap-4 mb-4">
                  <MapPinIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-gray-500 dark:text-gray-400">San Francisco, CA</span>
                </div>
                <div className="flex items-center gap-4">
                  <CalendarIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-gray-500 dark:text-gray-400">Application Deadline: July 15, 2023</span>
                </div>
              </CardContent>
              <CardFooter className="bg-gray-100 p-4 transition-colors group-hover:bg-gray-100 group-hover:text-gray-900 dark:bg-gray-800 dark:group-hover:bg-gray-800 dark:group-hover:text-gray-50">
                <Button variant="outline" className="w-full">
                  Apply Now
                </Button>
              </CardFooter>
            </Card>
            <Card className="relative overflow-hidden group">
              <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                <span className="sr-only">View job</span>
              </Link>
              <CardContent className="p-6">
                <h3 className="text-xl font-bold mb-2">Graphic Designer</h3>
                <p className="text-gray-500 mb-4 dark:text-gray-400">
                  Create visually stunning designs for a variety of digital and print media, including websites, social
                  media, and marketing materials.
                </p>
                <div className="flex items-center gap-4 mb-4">
                  <MapPinIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-gray-500 dark:text-gray-400">London, UK</span>
                </div>
                <div className="flex items-center gap-4">
                  <CalendarIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-gray-500 dark:text-gray-400">Application Deadline: August 1, 2023</span>
                </div>
              </CardContent>
              <CardFooter className="bg-gray-100 p-4 transition-colors group-hover:bg-gray-100 group-hover:text-gray-900 dark:bg-gray-800 dark:group-hover:bg-gray-800 dark:group-hover:text-gray-50">
                <Button variant="outline" className="w-full">
                  Apply Now
                </Button>
              </CardFooter>
            </Card>
            <Card className="relative overflow-hidden group">
              <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                <span className="sr-only">View job</span>
              </Link>
              <CardContent className="p-6">
                <h3 className="text-xl font-bold mb-2">Sales Representative</h3>
                <p className="text-gray-500 mb-4 dark:text-gray-400">
                  Responsible for generating new leads, closing sales, and maintaining strong relationships with
                  clients.
                </p>
                <div className="flex items-center gap-4 mb-4">
                  <MapPinIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-gray-500 dark:text-gray-400">Remote</span>
                </div>
                <div className="flex items-center gap-4">
                  <CalendarIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-gray-500 dark:text-gray-400">Application Deadline: September 1, 2023</span>
                </div>
              </CardContent>
              <CardFooter className="bg-gray-100 p-4 transition-colors group-hover:bg-gray-100 group-hover:text-gray-900 dark:bg-gray-800 dark:group-hover:bg-gray-800 dark:group-hover:text-gray-50">
                <Button variant="outline" className="w-full">
                  Apply Now
                </Button>
              </CardFooter>
            </Card>
            <Card className="relative overflow-hidden group">
              <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                <span className="sr-only">View job</span>
              </Link>
              <CardContent className="p-6">
                <h3 className="text-xl font-bold mb-2">Financial Analyst</h3>
                <p className="text-gray-500 mb-4 dark:text-gray-400">
                  Analyze financial data, create reports, and provide recommendations to support business
                  decision-making.
                </p>
                <div className="flex items-center gap-4 mb-4">
                  <MapPinIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-gray-500 dark:text-gray-400">New York, NY</span>
                </div>
                <div className="flex items-center gap-4">
                  <CalendarIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-gray-500 dark:text-gray-400">Application Deadline: October 1, 2023</span>
                </div>
              </CardContent>
              <CardFooter className="bg-gray-100 p-4 transition-colors group-hover:bg-gray-100 group-hover:text-gray-900 dark:bg-gray-800 dark:group-hover:bg-gray-800 dark:group-hover:text-gray-50">
                <Button variant="outline" className="w-full">
                  Apply Now
                </Button>
              </CardFooter>
            </Card>
            <Card className="relative overflow-hidden group">
              <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                <span className="sr-only">View job</span>
              </Link>
              <CardContent className="p-6">
                <h3 className="text-xl font-bold mb-2">Product Manager</h3>
                <p className="text-gray-500 mb-4 dark:text-gray-400">
                  Responsible for defining and executing the product strategy, roadmap, and feature development.
                </p>
                <div className="flex items-center gap-4 mb-4">
                  <MapPinIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-gray-500 dark:text-gray-400">San Francisco, CA</span>
                </div>
                <div className="flex items-center gap-4">
                  <CalendarIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-gray-500 dark:text-gray-400">Application Deadline: November 1, 2023</span>
                </div>
              </CardContent>
              <CardFooter className="bg-gray-100 p-4 transition-colors group-hover:bg-gray-100 group-hover:text-gray-900 dark:bg-gray-800 dark:group-hover:bg-gray-800 dark:group-hover:text-gray-50">
                <Button variant="outline" className="w-full">
                  Apply Now
                </Button>
              </CardFooter>
            </Card>
          </div>
        </div>
      </div>
    </div>
  )
}

function CalendarIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function MapPinIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
      <circle cx="12" cy="10" r="3" />
    </svg>
  )
}
